import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000}});
const page=await context.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto(process.env.TEST_URL||'http://localhost:4173/');
 await page.getByRole('heading',{name:'Meus treinos'}).waitFor();
 await page.screenshot({path:'test-results/desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Vamos treinar'}).click();
 await page.getByRole('button',{name:'Iniciar treino',exact:true}).click();
 await page.getByRole('button',{name:'Série 1',exact:true}).first().click();
 await page.getByRole('textbox',{name:'Carga de Aquecimento · Barra fixa',exact:true}).fill('20');
 await page.reload();
 await page.getByRole('button',{name:'Continuar treino'}).click();
 assert.equal(await page.getByRole('button',{name:'Série 1',exact:true}).first().getAttribute('aria-pressed'),'true');
 assert.equal(await page.getByRole('textbox',{name:'Carga de Aquecimento · Barra fixa',exact:true}).inputValue(),'20');
 await page.getByRole('button',{name:'Pausar',exact:true}).click();
 const paused=await page.locator('[data-time]').textContent();
 await page.waitForTimeout(1100);
 assert.equal(await page.locator('[data-time]').textContent(),paused);
 await page.getByRole('button',{name:'Ver execução'}).nth(1).click();
 assert.equal(await page.locator('iframe').count(),2);
 await page.getByRole('button',{name:'Fechar',exact:true}).click();
 await page.getByRole('button',{name:'Finalizar',exact:true}).click();
 await page.getByRole('button',{name:'Salvar e finalizar'}).click();
 await page.getByText('1 treinos',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Meu perfil',exact:true}).click();
 await page.getByLabel('Como podemos chamar você?').fill('Carlos');
 await page.getByRole('button',{name:'Salvar perfil'}).click();
 await page.reload();
 await page.getByRole('heading',{name:/Vamos nessa, Carlos/}).waitFor();
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'test-results/mobile.png',fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No horizontal overflow');
 await page.evaluate(()=>Promise.race([navigator.serviceWorker.ready,new Promise((_,reject)=>setTimeout(()=>reject(Error('Service worker install timeout')),15000))]));
 await context.setOffline(true);
 await page.reload();
 await page.getByRole('heading',{name:/Vamos nessa, Carlos/}).waitFor();
 await page.getByRole('button',{name:'Meus treinos',exact:true}).click();
 await page.getByRole('heading',{name:'Inferiores e abdômen',exact:true}).waitFor();
 assert.equal(errors.length,0,errors.join('\n'));
 console.log('PASS: session persistence, loads, pause, video links, finish, profile, mobile layout, offline reload.');
}finally{await browser.close();}
