import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:390,height:844}});
const page=await context.newPage();
page.setDefaultTimeout(15000);
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const testKey='sk-or-test-placeholder-not-a-real-key';
let mode='success',requests=0;
await page.route('https://openrouter.ai/api/v1/chat/completions',async route=>{
  requests++;
  assert.equal(route.request().headers().authorization,`Bearer ${testKey}`);
  assert.ok(!route.request().postData().includes('history'));
  if(mode==='error'){await route.fulfill({status:402,json:{error:{message:'private provider body'}}});return;}
  const result=mode==='question'?{message:'Qual foi a comida?',needsClarification:true,items:[]}:{message:'Estimativa para as porções informadas.',needsClarification:false,items:[{name:'Arroz',portion:'100 g',kcal:128},{name:'Feijão',portion:'100 g',kcal:76}]};
  await route.fulfill({json:{choices:[{finish_reason:'stop',message:{content:JSON.stringify(result)}}]}});
});
const go=async name=>page.getByRole('button',{name,exact:true}).first().click();
const send=async text=>{await page.getByLabel('O que você comeu?').fill(text);await go('Calcular e registrar');};
try{
  await page.goto(process.env.TEST_URL||'http://localhost:4173/');
  await go('Alimentação');
  await send('100 g arroz e feijão');
  assert.equal(requests,0);
  await go('Meu perfil');
  await page.getByLabel('Chave OpenRouter',{exact:true}).fill(testKey);await go('Salvar chave');
  await go('Alimentação');
  await send('100 g arroz e 100 g feijão');
  await page.getByText('Total estimado · salvo',{exact:true}).waitFor();
  await expect(page.locator('[data-food-day-total]')).toHaveText('204 kcal');
  await page.reload();await go('Alimentação');
  await expect(page.locator('[data-food-day-total]')).toHaveText('204 kcal');
  await go('Editar refeição');await page.getByLabel('Calorias de Arroz',{exact:true}).fill('150');await go('Salvar correção');
  await expect(page.locator('[data-food-day-total]')).toHaveText('226 kcal');
  await go('Editar refeição');
  await page.locator('[data-item-name]').first().fill('Arroz integral');
  await page.locator('[data-item-portion]').first().fill('120 g');
  await page.getByRole('button',{name:'Remover alimento',exact:true}).last().click();
  await go('+ Adicionar alimento');
  await page.locator('[data-item-name]').last().fill('Maçã');
  await page.locator('[data-item-portion]').last().fill('1 unidade');
  await page.locator('[data-item-kcal]').last().fill('76');
  await page.locator('#food-edit-form textarea').fill('Arroz integral e uma maçã');
  await expect(page.locator('[data-edit-total]')).toHaveText('226 kcal');
  await go('Salvar correção');
  await expect(page.locator('.user-message')).toContainText('Arroz integral e uma maçã');
  await expect(page.locator('.food-items')).toContainText('120 g');
  await go('Editar refeição');await page.locator('[data-item-kcal]').first().fill('900');await go('Cancelar');
  await expect(page.locator('[data-food-day-total]')).toHaveText('226 kcal');
  await go('Editar refeição');await page.locator('#food-edit-form textarea').fill('100 g de arroz e feijão');await go('Recalcular pelo relato');
  await expect(page.getByRole('button',{name:'Calcular e registrar',exact:true})).toBeEnabled();
  await expect(page.locator('[data-food-day-total]')).toHaveText('204 kcal');
  await go('Complementar relato');await page.getByLabel('O que você comeu?').fill('O arroz eram 100 g mesmo');await go('Recalcular');
  await expect(page.getByRole('button',{name:'Calcular e registrar',exact:true})).toBeEnabled();
  await page.getByText('Total estimado · salvo',{exact:true}).waitFor();
  assert.equal(await page.locator('.meal-thread').count(),1);await expect(page.locator('[data-food-day-total]')).toHaveText('204 kcal');
  mode='error';await go('Complementar relato');await page.getByLabel('O que você comeu?').fill('Mude para 200 g');await go('Recalcular');
  await expect(page.getByRole('button',{name:'Calcular e registrar',exact:true})).toBeEnabled();
  await expect(page.locator('[data-food-day-total]')).toHaveText('204 kcal');
  assert.ok(!(await page.locator('.user-message').innerText()).includes('200 g'));
  mode='error';await send('uma banana');await page.locator('.assistant-message').getByText(/Saldo insuficiente/).waitFor();
  await expect(page.locator('[data-food-day-total]')).toHaveText('204 kcal');
  mode='success';await go('Tentar novamente');await page.getByText('Total estimado · salvo',{exact:true}).nth(1).waitFor();
  assert.equal(await page.locator('.meal-thread').count(),2);await expect(page.locator('[data-food-day-total]')).toHaveText('408 kcal');
  mode='question';await send('comi um prato');await page.getByText('Qual foi a comida?',{exact:true}).waitFor();
  mode='success';await go('Responder');await page.getByLabel('O que você comeu?').fill('arroz e feijão');await go('Recalcular');
  await page.getByText('Total estimado · salvo',{exact:true}).nth(2).waitFor();
  await expect(page.locator('[data-food-day-total]')).toHaveText('612 kcal');
  const today=await page.locator('#food-day').inputValue();
  await page.locator('#food-day').fill('2020-01-02');await send('arroz e feijão');
  await page.getByText('Total estimado · salvo',{exact:true}).waitFor();
  await expect(page.locator('[data-food-day-total]')).toHaveText('204 kcal');
  assert.equal((await page.locator('[data-food-week-total]').innerText()).replace(/\s+/g,' '),'612 kcal est.');
  await go('Hoje');assert.equal(await page.locator('#food-day').inputValue(),today);
  await go('Excluir');await go('Excluir refeição');
  await expect(page.locator('[data-food-day-total]')).toHaveText('408 kcal');
  await page.screenshot({path:'test-results/nutrition-mobile.png',fullPage:true});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No mobile overflow');
  await go('Visão geral');assert.ok((await page.locator('[data-food-week-total]').innerText()).includes('408'));
  await go('Evolução');assert.ok((await page.locator('[data-food-week-total]').innerText()).includes('408'));
  await go('Meu perfil');
  const download=page.waitForEvent('download');await go('Exportar backup');
  const file=await download;const backup=JSON.parse(await readFile(await file.path(),'utf8'));
  assert.equal(backup.meals.length,3);assert.ok(!JSON.stringify(backup).includes(testKey));
  await page.locator('#import-file').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});
  await go('Restaurar backup');await go('Alimentação');await expect(page.locator('[data-food-day-total]')).toHaveText('408 kcal');
  await page.evaluate(()=>Promise.race([navigator.serviceWorker.ready,new Promise((_,reject)=>setTimeout(()=>reject(Error('SW timeout')),15000))]));
  await context.setOffline(true);await page.reload();await go('Alimentação');
  await expect(page.locator('[data-food-day-total]')).toHaveText('408 kcal');
  assert.equal(errors.length,0,errors.join('\n'));
  console.log('PASS: key setup, chat, persistence, corrections, clarification, API error/retry, daily/weekly totals, deletion, backup round-trip, mobile. API responses mocked; no paid API calls.');
}finally{await browser.close();}
